### PR TITLE
Datadirs ini

### PR DESCRIPTION
**Pull request by miniupnp**
search for game data and save games in different directories

see https://github.com/OpenDUNE/OpenDUNE/commit/4ca3cebd9e38cacb74b55cdc85f9ecb40c4dd269

### CODE REVIEW

**Comment by miniupnp** [comment]
I think that's a needed improvement : 
storing savegames in the same directory as game data is not good on modern OS : Users should not share the savegames !

**Comment by Mailaender** [comment]
I somehow can't get this to work. When I package version 0.9 I get:

```
opendune.ini file not found.
Cannot initialise files. Does ./data/ directory exist ?
```

**Comment by Mailaender** [comment]
Ideal solution would probably be https://github.com/OpenDUNE/OpenDUNE/issues/355.

**Comment by miniupnp** [comment]
> I somehow can't get this to work. When I package version 0.9 I get:
> 
> ```
> opendune.ini file not found.
> Cannot initialise files. Does ./data/ directory exist ?
> ```
> 
> I expected it to be in `~/.config/opendune` after reading the code.

is opendune.ini located in `~/.config/opendune/` ?

**Comment by Mailaender** [comment]
The folder is empty. The configuration file is not created.

**Comment by miniupnp** [comment]
> The folder is empty. The configuration file is not created.

why would it be created ?

**Comment by Mailaender** [comment]
That's what programs do. How else would settings be saved or the user be made aware that they can be changed.

**Comment by miniupnp** [comment]
@Mailaender what are you trying to do ?
https://github.com/OpenDUNE/OpenDUNE/blob/master/src/file.c#L33

**Comment by miniupnp** [comment]
> That's what programs do. How else would settings be saved or the user be made aware that they can be changed.

settings are not saved to the opendune.ini file. If it does not exists, default are used.
I think it is explained in the README and https://github.com/OpenDUNE/OpenDUNE/blob/master/bin/opendune.ini.sample

**Comment by Mailaender** [comment]
https://github.com/OpenDUNE/OpenDUNE/blob/9d8c9cf61d7770a058f1b8254b275647ab472f4d/src/file.c#L33-L34

How do I set this to `~/.opendune`? Sorry, I am quite new to C.

**Comment by miniupnp** [comment]
> https://github.com/OpenDUNE/OpenDUNE/blob/9d8c9cf61d7770a058f1b8254b275647ab472f4d/src/file.c#L33-L34
> 
> How do I set this to `~/.opendune`? Sorry, I am quite new to C.

you don't. I'm afraid tilde expansion is done by the shell.
I still don't understand what you are trying to do. To install a system OpenDUNE you would probably set DUNE_DATA_DIR to either` /usr/local/share/opendune` or `/usr/share/opendune`. And if that is a custom build, if `./data` is not OK, the user can customize by setting `datadir=` in the `opendune.ini`.

**Pull request merged**
