### PR TITLE
Fix #93 linux osx

### LINKED ISSUE #93: Linux - deadlock between alsa and xcb
http://bugs.opendune.org/view.php?id=93

svuorela wrote:
...according to #opendune it is related to alsa and xcb with one doing free and the other malloc at the same time.

The backtrace is here:

gdb) bt
#0 0xb7796424 in __kernel_vsyscall ()
0000001 0xb753adb1 in __lll_lock_wait_private () at ../nptl/sysdeps/unix/sysv/linux/i386/i686/../i486/lowlevellock.S:95
0000002 0xb74d1ba7 in _L_lock_9661 () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
0000003 0xb74d03d6 in *__GI___libc_free (mem=0xb201efd8) at malloc.c:3736
0000004 0xb72e4959 in dequeue_pending_request (dpy=<optimized out>, req=<optimized out>) at ../../src/xcb_io.c:195
0000005 0xb72e5ccf in _XReply (dpy=0x8890a40, rep=0xbfaf7d80, extra=0, discard=1) at ../../src/xcb_io.c:638
0000006 0xb72e1236 in XSync (dpy=0x8890a40, discard=0) at ../../src/Sync.c:44
0000007 0xb76f1410 in ?? () from /usr/lib/libSDL-1.2.so.0
0000008 0xb76e3a6e in SDL_UpdateRects () from /usr/lib/libSDL-1.2.so.0
0000009 0xb76e3bd1 in SDL_UpdateRect () from /usr/lib/libSDL-1.2.so.0
0000010 0x0809adfc in Video_Tick () at /home/pusling/games/opendune/opendune-0.7-source/src/video/video_sdl.c:524
0000011 0x080944b6 in Timer_InterruptRun () at /home/pusling/games/opendune/opendune-0.7-source/src/timer.c:103
0000012 <signal handler called>
0000013 _int_malloc (av=<optimized out>, bytes=<optimized out>) at malloc.c:4348
0000014 0xb74cfc1b in __libc_calloc (n=1, elem_size=36) at malloc.c:4065
0000015 0xb741a1ee in pa_xmalloc0 () from /usr/lib/libpulse.so.0
0000016 0xb7401681 in ?? () from /usr/lib/libpulse.so.0
0000017 0xb70dec79 in pa_pdispatch_register_reply () from /usr/lib/libpulsecommon-0.9.23.so
0000018 0xb740ccdf in pa_stream_update_timing_info () from /usr/lib/libpulse.so.0
0000019 0xb740cf4d in ?? () from /usr/lib/libpulse.so.0
0000020 0xb7410586 in pa_stream_cork () from /usr/lib/libpulse.so.0
0000021 0xb7764480 in ?? () from /usr/lib/i386-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so
0000022 0xb7650b69 in ?? () from /usr/lib/i386-linux-gnu/libasound.so.2
0000023 0xb76045df in snd_pcm_start () from /usr/lib/i386-linux-gnu/libasound.so.2
0000024 0xb760c777 in ?? () from /usr/lib/i386-linux-gnu/libasound.so.2
0000025 0xb76503bf in ?? () from /usr/lib/i386-linux-gnu/libasound.so.2
0000026 0xb76052a4 in snd_pcm_writei () from /usr/lib/i386-linux-gnu/libasound.so.2
0000027 0x080562aa in DSP_Play (data=0x88cad72 "\001(\"") at /home/pusling/games/opendune/opendune-0.7-source/src/audio/dsp_alsa.c:134
0000028 0x08055994 in Driver_Voice_Play (data=0x88cad58 "Creative Voice File\032\032", arg0A=11) at /home/pusling/games/opendune/opendune-0.7-source/src/audio/driver.c:272
0000029 0x08059006 in Voice_PlayAtTile (voiceID=42, position=...) at /home/pusling/games/opendune/opendune-0.7-source/src/audio/sound.c:128
0000030 0x08098e13 in Unit_CreateBullet (position=..., type=UNIT_MISSILE_TURRET, houseID=1 '\001', damage=30, target=16420) at /home/pusling/games/opendune/opendune-0.7-source/src/unit.c:1936
0000031 0x08089cf0 in Script_Structure_Fire (script=0x80c9074) at /home/pusling/games/opendune/opendune-0.7-source/src/script/structure.c:534
0000032 0x08088512 in Script_Run (script=0x80c9074) at /home/pusling/games/opendune/opendune-0.7-source/src/script/script.c:445
0000033 0x0808fe5f in GameLoop_Structure () at /home/pusling/games/opendune/opendune-0.7-source/src/structure.c:333
0000034 0x08082c8c in GameLoop_Main () at /home/pusling/games/opendune/opendune-0.7-source/src/opendune.c:2281
0000035 0x08082eeb in main (argc=1, argv=0xbfaf8ea4) at /home/pusling/games/opendune/opendune-0.7-source/src/opendune.c:2396

### PR DESCRIPTION
**Pull request by miniupnp**
Don't change anything with Win32 code which works perfectly !
Linux/OS X : remove any multithreading code, don't execute real code in signal handler

### CODE REVIEW

**Comment by fukanchik** [comment]
If last notes of start music are still playing when "Dynasty Selection" screen opens the game hangs.

1) Cursor is hidden
2) Clicking around does not have any effect
3) Music is still playing

**Comment by miniupnp** [comment]
thanks for testing! I guess it is because some sleepIdle() call is missing !

**Comment by miniupnp** [comment]
@fukanchik hum I can't reproduce right now...

**Comment by miniupnp** [comment]
@fukanchik : you can help by running in gdb, and giving the backtrace when the game hangs

**Comment by fukanchik** [comment]
I'm travelling this week,so can't do that until December. Without sound the game works fine.

**Comment by miniupnp** [comment]
what is your setup ? OS X ? Linux ?

**Comment by fukanchik** [comment]
Core i7 Ubuntu 64. Pulseaudio

**Comment by miniupnp** [comment]
@fukanchik have you been able to test within GDB ?

**Comment by fukanchik** [comment]
(gdb) info threads
  Id   Target Id         Frame 
  2    Thread 0x7fffee1ff700 (LWP 6166) "threaded-ml" 0x00007ffff757c12d in poll () at ../sysdeps/unix/syscall-template.S:81
* 1    Thread 0x7ffff7fae740 (LWP 6162) "opendune" 0x00007ffff754fedd in pause () at ../sysdeps/unix/syscall-template.S:81

(gdb) bt
#0  0x00007ffff754fedd in pause () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000044137d in SleepAndProcessBackgroundTasks () at /tmp/0/OpenDUNE/src/timer.c:134
#2  0x000000000042116d in GUI_PickHouse () at /tmp/0/OpenDUNE/src/gui/gui.c:1696
#3  0x000000000040efb1 in GameLoop_Main () at /tmp/0/OpenDUNE/src/opendune.c:1003
#4  main (argc=<optimized out>, argv=<optimized out>) at /tmp/0/OpenDUNE/src/opendune.c:1224

Second thread:
(gdb) bt
#0  0x00007ffff757c12d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff6b68031 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007ffff6b5983c in pa_mainloop_poll () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#3  0x00007ffff6b59ece in pa_mainloop_iterate () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007ffff6b59f80 in pa_mainloop_run () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#5  0x00007ffff6b67fe3 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#6  0x00007ffff5cdcf08 in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-4.0.so
#7  0x00007ffff610e182 in start_thread (arg=0x7fffee1ff700) at pthread_create.c:312
#8  0x00007ffff758947d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by miniupnp** [comment]
OK so Pulse audio is creating its own thread...

**Comment by miniupnp** [comment]
Looks like the problem is in DSP_GetStatus().
it might works better with dsp_sdl.c instead of dsp_alsa.c

**Comment by miniupnp** [comment]
(gdb) print s_bufferDone

**Comment by miniupnp** [comment]
I installed PulseAudio and now the sounds (voices) don't play anymore... both with dsp_alsa.c and dsp_sdl.c. 
The game hangs after house selection because it waits for the speech to finish playing which is never the case :(
```
while (Sound_StartSpeech()) sleepIdle();
```

**Comment by miniupnp** [comment]
@fukanchik  does Speech / digitized sounds play elsewhere (Intro / loaded games) ?

**Comment by miniupnp** [comment]
BTW I have the exact same bug (music but no sound/voice, hang at house selection screen) using master so the bug is clearly not about this branch but about PulseAudio :(

**Comment by miniupnp** [comment]
@fukanchik : have you the same issue with https://github.com/miniupnp/OpenDUNE/tree/pulseaudio_test
(preliminary pulse audio playback implementation)

**Comment by fukanchik** [comment]
It doesn't link on my machine:
/usr/bin/ld.bfd.real: audio/dsp_pulse.o: undefined reference to symbol 'pa_mainloop_iterate@@PULSE_0'

i hadto manually add -lpulse into generated objs/debug/Makefile

It stillhangs. This is what printed to console:

opendune.ini file not found.
s_timer_count = 4
DSP_Play() data=0x1fe7e80 freq=11764
DSP_stream_notify_cb(0x1ff3650, (nil)) state=1
DSP_stream_notify_cb(0x1ff3650, (nil)) state=2
DSP_stream_success_cb(0x1ff3650, 1, (nil))

Now there's only one thread.

Stack trace:
(gdb) bt
#0  0x00007ffff7306ec0 in __pause_nocancel () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000044140d in SleepAndProcessBackgroundTasks () at /tmp/0/OpenDUNE/src/timer.c:134
#2  0x00000000004211fd in GUI_PickHouse () at /tmp/0/OpenDUNE/src/gui/gui.c:1696
#3  0x000000000040f0a1 in GameLoop_Main () at /tmp/0/OpenDUNE/src/opendune.c:1003
#4  main (argc=<optimized out>, argv=<optimized out>) at /tmp/0/OpenDUNE/src/opendune.c:1224

**Comment by miniupnp** [comment]
@fukanchik does sound/speech play (during intro for example)

**Comment by fukanchik** [comment]
Yes, sound and speech play

**Comment by miniupnp** [comment]
@fukanchik and everything work on master ?

**Comment by miniupnp** [comment]
@fukanchik Can you confirm sound works well for you on master branch ?
By the way, I improved my PulseAudio code

**Comment by fukanchik** [comment]
I will look at it tonight.

**Comment by fukanchik** [comment]
All three branches do not work anymore with the same simptom:
1) Yours
2) master
3) mine  which was branched from master long time ago and was working before
so looks like there is something wrong with Pulseaudio on my machine .

**Comment by rofl0r** [comment]
nice to see this fixed, however /me wonders why it wasn't just fixed by merging my PR which worked perfectly https://github.com/OpenDUNE/OpenDUNE/pull/174/files

**Comment by miniupnp** [comment]
@rofl0r main difference with your code is that nothing is changed under Windows (everything worked well under windows, why change it ?)

**Comment by rofl0r** [comment]
because having one universal codepath is nicer than having 2 under ifdef's, i guess

**Comment by rofl0r** [comment]
(the win32 codepath used windows specific tricks even though its perfectly possible to do everything in a portable way)

**Pull request merged**
