### PR TITLE
Added MIDI Fluid support for Raspberry PI

### PR DESCRIPTION
**Pull request by NovaCoderX**
Added MIDI Fluid support for Raspberry PI, also fixed up SDL DSP to correctly calculate the playback rate.   Had to update drivers.c because SDL_InitSubSystem() before enabling MIDI.

### CODE REVIEW

**Comment by miniupnp** [comment]
@NovaCoderX it looks like it is missing some build upgrade to build midi_fluid.c

**Comment by NovaCoderX** [comment]
Hi Bernard,
Yes it needs the build script updated, sorry about that.   I'm not so good with updating build scripts (I just built it manually for my local testing).

Chris 
    On Friday, 18 August 2023 at 09:10:47 GMT+10, Thomas BERNARD ***@***.***> wrote:  
 
 


@NovaCoderX it looks like it is missing some build upgrade to build midi_fluid.c

**Comment by miniupnp** [comment]
I will have a look and try to make it work on my FreeBSD machine ;)

**Comment by NovaCoderX** [comment]
Great, thanks 👍
    On Monday, 21 August 2023 at 18:34:54 GMT+10, Thomas BERNARD ***@***.***> wrote:  
 
 


I will have a look and try to make it work on my FreeBSD machine ;)

**Comment by miniupnp** [comment]
I have split the commit and added the configure stuff. see #388

**Pull request closed without merging**
