### PR TITLE
Update config.lib

### PR DESCRIPTION
**Pull request by flip111**
fix link time optimization flag

### CODE REVIEW

**Comment by miniupnp** [comment]
can you be more specific about what is fixed by your commit ?

I prefer detailed commit messages.

**Comment by flip111** [comment]
`$cxx_build` does not exist so gcc is not called to report specifications

**Comment by miniupnp** [comment]
can you amend the commit message to include this explanation ?

**Comment by flip111** [comment]
I submit https://github.com/OpenDUNE/OpenDUNE/pull/330 instead

**Pull request closed without merging**
