### PR TITLE
Introduce command line option '-d' to select data directory

### PR DESCRIPTION
**Pull request by caiiiycuk**

### CODE REVIEW

**Comment by miniupnp** [comment]
I'm thinking maybe the behaviour should be different between windows and linux.
It is quite common for windows apps to have everything in \program files\ along with the .exe file
while linux applications have binary in /usr/local/bin , data in /usr/local/share/... etc.

**Comment by caiiiycuk** [comment]
@TrueBrain you can close this PR if community decide to introduce ini file.

**Comment by miniupnp** [comment]
see https://github.com/miniupnp/OpenDUNE/tree/datadirs_ini
is it ok ?

**Comment by caiiiycuk** [comment]
Yes it is.

**Pull request closed without merging**
