### PR TITLE
Atari TOS port (Atari Falcon030 and TT)

### PR DESCRIPTION
**Pull request by miniupnp**
add code to support 256 colors capables Atari 68k machines : TT and Falcon.

The game is playable on 32MHz TT, a bit slow on a plain 16Mhz Falcon

Precompiled binaries available here : http://nanard.free.fr/opendune/

Still work to do to support sound, MIDI music, etc.

### CODE REVIEW

**Comment by Xaroth** [comment]
At times like these I wish I still had an Atari... would love to see that in action

**Comment by miniupnp** [comment]
@Xaroth : I have only a STE and a MegaST, I used Hatari to test. It emulates pretty well a TT or Falcon.

**Comment by miniupnp** [comment]
you can discuss about the port here : http://www.atari-forum.com/viewtopic.php?f=26&t=29873

**Comment by TrueBrain** [comment]
Seriously awesome work :D Also exactly in the idea of the project .. very cool! *top hat*

**Pull request merged**
