### PR TITLE
fixed installation scripts

### PR DESCRIPTION
**Pull request by lucasso**
removed installing never defined ICON_DIR, added installing DATA_DIR and DOC_DIR

I found make not working on Ubuntu. One variable ICON_DIR is never used.
Another dir DOC_DIR is never created by make.
I fixed it. Please review.

### CODE REVIEW

**Comment by miniupnp** [comment]
I'm not sure where the doc should be installed

**Comment by lucasso** [comment]
I remember, you were correct about location and I was wrong.
Can you take care of proper merge?

Regards,
Łukasz

2016-02-11 15:32 GMT+01:00 Thomas BERNARD <notifications@github.com>:

> I'm not sure where the doc should be installed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenDUNE/OpenDUNE/pull/244#issuecomment-182889197>.
>



-- 
Łukasz Ślusarczyk
  http://www.lucasso.pl

**Comment by miniupnp** [comment]
so it should be /usr/local/share/doc/opendune ?

**Comment by lucasso** [comment]
yes
/usr/local/share/doc/opendune
I checked some other linux games where they put such files.

Łukasz

2016-02-11 15:34 GMT+01:00 Thomas BERNARD <notifications@github.com>:

> so it should be /usr/local/share/doc/opendune ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenDUNE/OpenDUNE/pull/244#issuecomment-182890342>.
>



-- 
Łukasz Ślusarczyk
  http://www.lucasso.pl

**Pull request merged**
