### PR TITLE
Adding generate.vbs to (re)create VS project files

### PR DESCRIPTION
**Pull request by drnovice**
Adding generate.vbs to (re)create VS project files.
Adding vs80 project file version, and correct vs120 and vs140 project files.

### CODE REVIEW

**Comment by drnovice** [comment]
This PR refers to https://github.com/OpenDUNE/OpenDUNE/pull/269#issuecomment-219252214

**Comment by drnovice** [comment]
Only two openpoints:
a) is it better maybe remove "opendune_vs90.vcproj.user" from git, since it's only an user personal configuration file?
b) what about **.s** files? when choose them by the #if into source.list, they have to included to the build?

**Comment by miniupnp** [comment]
1) I will have a look at opendune_vs90.vcproj.user
2) .s files are only needed for Atari version, do not bother to include them in Visual studio project

assembler files for Win32 would be .asm

**Comment by miniupnp** [comment]
ref : https://github.com/miniupnp/OpenDUNE/tree/pr273 

I will test before merging :)

**Comment by drnovice** [comment]
Added correction about version_vs120 and version_vs140 files

**Comment by miniupnp** [comment]
rebased/merged in master

**Pull request closed without merging**
