### PR TITLE
Adding VS2013 (v12) and VS2015 (v14) project and solution files to modern IDEs

### PR DESCRIPTION
**Pull request by drnovice**
We have worked to add SDL2 support under Windows (built tested on VS2013).

At the moment to use SDL2, exclude from build:
video_win32.c
thread_win32.c

and add for build:
video_sdl2.c
thread_sdl.c

I had to add #include <stdio.h> on video_sdl2.c because of without it can't complile on VS.
Moreover we have to add WITH_SDL2 on VS Preprocessor options and use Windows (/SUBSYSTEM:WINDOWS) on System options.

Soon I'll give a tutorial to use SDL2 on VS and Windows.

Thanks to segrax for support.

### CODE REVIEW

**Comment by drnovice** [comment]
To use window resize just press Plus (increase) / Minus (decrease) keys, F11 for Fullscreen.

**Comment by miniupnp** [comment]
ok, so it is not window "free" resizing like I implemented, it's just runtime change of scale factor.

I guess many changes have nothing to do in this pull request. Like VS2012 / 2015 project files. Which are good but should be integrated with the existing build system and put in a separate PR

**Comment by Xaroth** [comment]
While I can see the value of having runtime change of scale factor, I must press that we cannot accept this PR as-is, as it doesn't conform with our coding style ( https://github.com/OpenDUNE/OpenDUNE/wiki/Coding-Style ).

Also, as @miniupnp mentions, while project files are nice and good to have, they really ought to be included into our build system, and put in a separate PR so we can more easily track how/what/why things were changed.

**Comment by miniupnp** [comment]
I keep this PR open so I could see what can be cherry-picked here.

**Comment by drnovice** [comment]
Sorry about the particulars, I'm just happy to share with you all the patch about resizing ways used for opendune.
I also tell you it's the first time I push on github a more substantial change and never I opened pull request, so I wanted to recap into once all changes I think are missing about opendune currently: one of these is just new VS project files, since VS2008/VS2010 are becoming deprecated, and since they are on the original master project I believe that may be there rightly.

I'll try to rewrite the changes with coding style suggested, and trying to split as possible the topics to focalize them better about code changes.

Thanks to have look at the code anyway.

**Comment by drnovice** [comment]
Only I would know thw things that I couldn't understand on master code:

1) Why the using of /* Fall Through */ on case SDL_KEYDOWN, and the use of flag by function calling: Video_Key_Callback(scancode **| (keyup ? 0x80 : 0x0)**) ?

2) Why Video_Key_Callback (and many others) doesn't respect the "CamelCase for function names, no _ " rule about opendune Coding Style ?

**Comment by miniupnp** [comment]
1) OpenDUNE is based on original Dune II code which process PC keyboard scancodes.
high bit is 1 for key up, 0 for key down.
2) I don't know :) was done that way in https://github.com/OpenDUNE/OpenDUNE/commit/b4fce9f3150d621deb5b5b1fe800d4eff6f8a047 and never fixed since.

That's not important that 100% of the code complies perfectly with Coding style, it's more important that new code complies

**Comment by Xaroth** [comment]
The underscores you can see as namespace delimitors.. since C doesn't do OO, you need a clear schema to identify where something belongs.. This is also the reason of the no underscore rule for function names .. Video_Window_Resize would be seen as Video->Window->Resize, which sounds like a function call to resize the window, where Video_WindowResize sounds more like a WindowResize event handler for the Video system.

Hope this clears it up a tad.

**Comment by drnovice** [comment]
Thanks for clarifications.
What is the  real reason of using Winapi (under Windows)? Is the different behaviour about threads between Linux and Windows for SDL?

Do you like using SDL2 even under Windows? We could decide to use this graphic framework as primary default choice, for backward compatibility leave SDL1.2 and WinAPI as secondary choice.

**Comment by miniupnp** [comment]
WinAPI version is working very well I think. Making everything work properly with SDL / SDL2 was more difficult.

Today, building the Win32 version is very straight forward, there is absolutely no need for any additional library. I think Win32 API should stay the default : SDL2 may give some more features, but I'm afraid old PC's under XP and without 3D card would then not be able to run the game anymore. We've seen many users playing OpenDune on old netbooks !

**Comment by drnovice** [comment]
If opendune gives support to old platforms, sure we have to continue to give that support, but we have to look at even the new systems and ways to make opendune a suitable product for new IDEs and OS.

**Comment by segrax** [comment]
One of the main driving reasons behind this,
is if you load the current release (0.7) with a 2560x1440 resolution.. the window is tiny, and there is no way to resize it without compiling it yourself, and setting the scaler.

So we took the same approach used which was used in OpenFodder and applied it here, mostly because its simple/user friendly and doesn't require a restart (press + or - to change the window size, auto into full screen once max window size has been reached - while maintaining the aspect ratio)

we're also wondering if there will be a replacement for the existing 'visual studio project builder'.. as it requires BASH.

**Comment by drnovice** [comment]
I have reset the commits about our fork, so first we can working to this micro-change and then do the SDL changes.

**Comment by TrueBrain** [comment]
OpenTTD these days has a vbs variant of the VS generate script; possibly that can help you out?

https://github.com/OpenTTD/OpenTTD/tree/master/projects

It is a near copy, so it shouldn't be too hard to port it to OpenDUNE. Just my 2 pennies :)

**Comment by drnovice** [comment]
Actually the files (.sln & .vcxproj) are already there and correctly created. What else for accept the PR?

**Comment by miniupnp** [comment]
1) Testing
2) testing of vcxproj generation from the source.list

**Comment by drnovice** [comment]
For reasons of time I can't install and try for linux/unix nor other non-Windows based system.
I have chosen to test opendune only under Windows.
Could you test it if you have all configured stuff?

I also wounder why are Visual Studio using in a non-Windows system?

**Comment by miniupnp** [comment]
> For reasons of time I can't install and try for linux/unix nor other non-Windows based system.
> I have chosen to test opendune only under Windows.
> Could you test it if you have all configured stuff?

Don't misunderstand what I'm saying. I always test PR before merging.

> I also wounder why are Visual Studio using in a non-Windows system?
I don't understand your question.

**Comment by drnovice** [comment]
The added files (new .sln & .vcxproj from VS2013/2015) are tested under Windows 10.

Now, how can I testing of vcxproj generation from the source.list ?
It's related to determineversion.vbs and "generate" file into projects folder?

**Comment by miniupnp** [comment]
I'm trying with Visual Studio Express 2015 for Windows 10 :
`version_vs140.vcxproj : warning  : Impossible de trouver les outils de build pour Visual Studio 2010 (v100). Installez Visual Studio 2010 (v100) pour générer à l'aide des outils de build Visual Studio 2010 (v100).`

**Comment by miniupnp** [comment]
hum I need to try with community edition

**Comment by drnovice** [comment]
Did you try with VS Community?
I finally managed a new generate.vbs to create .vcproj files (v80 and v90) and .vcxproj files (v100, v120 and v140) by .in pre-built files.

Only a few of things:
a) what about .sln files? Why don't you create even them with .in version?
b) what about \src\depend\depend.cpp? If it isn't currently into souce.list, VS filter can't be created, also it's completely missing into VS project (physical files exists, but it isn't excluded, nor included from build)
c) what about rev.c file? By default, it must be included or excluded from build?

**Comment by miniupnp** [comment]
you can open new PR to add generate.vbs

a) the .sln don't change so...
b) depend.cpp is used with Makefile build.VS has its own dependency checking system
c) rev.c is included...

**Comment by drnovice** [comment]
If rev.c have to be included from the build, why is it renamed like "rev.c.in" into repository on /src/ filter-folder? How does it work?

**Comment by miniupnp** [comment]
rev.c is generated from rev.c.in
Have a look at the "version" project to see how it works

**Comment by drnovice** [comment]
Ok and about os/thread_sdl.c ?

**Comment by miniupnp** [comment]
os/thread_sdl.c is not used anymore

**Comment by drnovice** [comment]
I used it for SDL/SDL2 patching on Win32 alternative, otherwise it can't work properly.

**Comment by miniupnp** [comment]
This PR is closed. Please open a new PR for Win32-SDL2 build.

**Comment by drnovice** [comment]
I'll open 2 other PR: one about generate.vbs and one for sdl/sdl2 for win32 build with window zoom in/out.

**Pull request merged**
