### PR TITLE
Add Haiku support

### LINKED ISSUE #324: Keyboard issue on Haiku (my port)
Good evening,

this is not exactly an issue but rather a request for advices/support.

I'm porting OpenDUNE on Haiku. The port works and the game is playable, although with no sound, with a minor patch you can fine [here](https://github.com/theclue/haikuports/blob/opendune/games-strategy/opendune/patches/opendune-0.9.patchset) (mostly related to system paths). This is based on OpenDUNE v0.9 release.

The game builds well on both SDL and SDL2, but with the latter is extremely slow, so I rever back to SDL for now.

But I have a serious issue with keyboard: basically all the keys are totally messed up (for example, hitting 'n' send the code for '9'). I noticed it while naming a savegame.

The issue goes away with SDL2 (but as I said, the game is unplayable with SDL2).

Do you have an idea on what could cause the issue?

### PR DESCRIPTION
**Pull request by lonemadmax**
Closes #324

### CODE REVIEW

**Comment by miniupnp** [comment]
why does it tries to build error_haiku.cpp under Linux ?
```
[SRC] Compiling os/error_haiku.cpp

/home/travis/build/OpenDUNE/OpenDUNE/src/os/error_haiku.cpp:5:19: fatal error: Alert.h: No such file or directory
```

**Comment by miniupnp** [comment]
that should fix it : https://github.com/miniupnp/OpenDUNE/commit/0e46ff07df05a1156fc9d3c05da8b735ea7c7f7d

**Review by miniupnp — CHANGES_REQUESTED** [review]
Waiting to be sure if the build fix is OK

**Comment by miniupnp** [comment]
we should also update the README etc.

**Comment by lonemadmax** [comment]
Wow, I didn't expect this to go so fast and smooth. You've even corrected my breaking other platforms and updated the doc! Thank you.

**Pull request merged**
